name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Vlang
        uses: vlang/setup-v@v1.3
        with:
          stable: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Build ${{ github.event.repository.name }}
        run: v -enable-globals .

      - name: Run Tests
        run: | 
          v -enable-globals test ./server
          v -enable-globals test ./q
